//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Actions/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Turn text"",
            ""id"": ""bd54d0fc-b86e-4bce-8ea2-93e0529c3092"",
            ""actions"": [
                {
                    ""name"": ""Next Phrase"",
                    ""type"": ""Button"",
                    ""id"": ""5e1e6ce2-7e15-4090-9b78-852e782cca62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a0a92467-9529-4329-bb25-1e5f41f6bf5f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Phrase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Turn text
        m_Turntext = asset.FindActionMap("Turn text", throwIfNotFound: true);
        m_Turntext_NextPhrase = m_Turntext.FindAction("Next Phrase", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Turn text
    private readonly InputActionMap m_Turntext;
    private List<ITurntextActions> m_TurntextActionsCallbackInterfaces = new List<ITurntextActions>();
    private readonly InputAction m_Turntext_NextPhrase;
    public struct TurntextActions
    {
        private @Controls m_Wrapper;
        public TurntextActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextPhrase => m_Wrapper.m_Turntext_NextPhrase;
        public InputActionMap Get() { return m_Wrapper.m_Turntext; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TurntextActions set) { return set.Get(); }
        public void AddCallbacks(ITurntextActions instance)
        {
            if (instance == null || m_Wrapper.m_TurntextActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TurntextActionsCallbackInterfaces.Add(instance);
            @NextPhrase.started += instance.OnNextPhrase;
            @NextPhrase.performed += instance.OnNextPhrase;
            @NextPhrase.canceled += instance.OnNextPhrase;
        }

        private void UnregisterCallbacks(ITurntextActions instance)
        {
            @NextPhrase.started -= instance.OnNextPhrase;
            @NextPhrase.performed -= instance.OnNextPhrase;
            @NextPhrase.canceled -= instance.OnNextPhrase;
        }

        public void RemoveCallbacks(ITurntextActions instance)
        {
            if (m_Wrapper.m_TurntextActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITurntextActions instance)
        {
            foreach (var item in m_Wrapper.m_TurntextActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TurntextActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TurntextActions @Turntext => new TurntextActions(this);
    public interface ITurntextActions
    {
        void OnNextPhrase(InputAction.CallbackContext context);
    }
}
